# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bcce914dd8f2dfc3dfd7d2eead09726277fd939d3b7a289dc0ace14c2d69dade86a41ca1f8a15b0c8758805a1895164c8effe7e1282094214b0ce3321b2c055

test:
  secret_key_base: bc644ac3686d8c7d7208fcf8cd6eaa661c0b6545d9cfa80ec49232bfc92307a008d2f06bb725d37863215fd5fda2d5bf9c036df9e0f8670e3c00cbe18b56e95c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
